// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lagjosipigbrywbutuwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZ2pvc2lwaWdicnl3YnV0dXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTk2OTYsImV4cCI6MjA1ODY3NTY5Nn0.hVcwE5Ju6XE2oktFZdSCXAqD2gi4-qZvYb_zgTEkL5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);